### ISSUE TITLE
感觉相同的confidence score与IOU threshold下人识别的效果不如通用的YOLOv3。。。

### ISSUE THREAD

**Issue by JohnnyHopp** [Zyjacya-In-love/Pedestrian-Detection-on-YOLOv3_Research-and-APP#6]

**Comment by Zyjacya-In-love** [comment]
是的，https://github.com/qqwweee/keras-yolo3 这份 Keras 实现的 YOLOv3 的精度基本没有其他版本的高；但是代码写的易读，方便学习 YOLOv3 的具体网络结构设计和各层实现。

**Comment by JohnnyHopp** [comment]
> 是的，https://github.com/qqwweee/keras-yolo3 这份 Keras 实现的 YOLOv3 的精度基本没有其他版本的高；但是代码写的易读，方便学习 YOLOv3 的具体网络结构设计和各层实现。

谢谢，还是很不错的尝试！有一个疑问就是，如果相同YOLO模型设计下，只用人的class来训练的话，能达到比通用YOLO检测人更高的精度吗？或者您这边有什么其他的repo或他人的比较结果可供参考下吗？

**Comment by Zyjacya-In-love** [comment]
> > 是的，https://github.com/qqwweee/keras-yolo3 这份 Keras 实现的 YOLOv3 的精度基本没有其他版本的高；但是代码写的易读，方便学习 YOLOv3 的具体网络结构设计和各层实现。
> 
> 谢谢，还是很不错的尝试！有一个疑问就是，如果相同YOLO模型设计下，只用人的class来训练的话，能达到比通用YOLO检测人更高的精度吗？或者您这边有什么其他的repo或他人的比较结果可供参考下吗？

很遗憾，我没有尝试过在相同数据集下测试这个事情，没法下判断；然后我这也没有其他人的结果可以提供。
